
app:
  storage:
    type: S3 # s3 | local
    local:
      base-path: ./uploads

aws:
  s3:
    bucket-name: master-isok
    endpoint: http://localhost:4566 # LocalStack
  region: us-east-1
  access-key: test
  secret-key: test



jwt:
  secret: 'your-256-bit-secret-key-1234567890abcdef'
  access-token-expiration: '3600000'
  refresh-token-expiration: '604800000'

server:
  port: 8080
  servlet:
    context-path: /api/v1